/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package librecat.org.catmandu.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int DOSET = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int UNLESS = 12;
  /** RegularExpression Id. */
  int NAME = 13;
  /** RegularExpression Id. */
  int NAME_REST = 14;
  /** RegularExpression Id. */
  int S_ARG = 15;
  /** RegularExpression Id. */
  int L_ARG = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int DIGITS = 18;
  /** RegularExpression Id. */
  int QQ_STRING = 19;
  /** RegularExpression Id. */
  int QQ_CHARS = 20;
  /** RegularExpression Id. */
  int QQ_CHAR = 21;
  /** RegularExpression Id. */
  int Q_STRING = 22;
  /** RegularExpression Id. */
  int Q_CHARS = 23;
  /** RegularExpression Id. */
  int Q_CHAR = 24;
  /** RegularExpression Id. */
  int BARE_STRING = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"do\"",
    "\"doset\"",
    "\"end\"",
    "\"else\"",
    "\"if\"",
    "\"unless\"",
    "<NAME>",
    "<NAME_REST>",
    "<S_ARG>",
    "<L_ARG>",
    "<INT>",
    "<DIGITS>",
    "<QQ_STRING>",
    "<QQ_CHARS>",
    "<QQ_CHAR>",
    "<Q_STRING>",
    "<Q_CHARS>",
    "<Q_CHAR>",
    "<BARE_STRING>",
    "\"(\"",
    "\")\"",
  };

}
