/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package librecat.org.catmandu.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int NAME_REST = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int DIGITS = 10;
  /** RegularExpression Id. */
  int QQ_STRING = 11;
  /** RegularExpression Id. */
  int QQ_CHARS = 12;
  /** RegularExpression Id. */
  int QQ_CHAR = 13;
  /** RegularExpression Id. */
  int Q_STRING = 14;
  /** RegularExpression Id. */
  int Q_CHARS = 15;
  /** RegularExpression Id. */
  int Q_CHAR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<NAME>",
    "<NAME_REST>",
    "<INT>",
    "<DIGITS>",
    "<QQ_STRING>",
    "<QQ_CHARS>",
    "<QQ_CHAR>",
    "<Q_STRING>",
    "<Q_CHARS>",
    "<Q_CHAR>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
